export const SET_CONVERTER_TYPE = 'SET_CONVERTER_TYPE';
export const SET_CONVERTER_FROM = 'SET_CONVERTER_FROM';
export const SET_CONVERTER_TO = 'SET_CONVERTER_TO';
export const SET_CONVERTER_QUANTITY = 'SET_CONVERTER_QUANTITY';
export const SET_CONVERTER_TABLO = 'SET_CONVERTER_TABLO';
export const LOAD_CURRENCY = 'LOAD_CURRENCY';
export const SET_NOTES = 'SET_NOTES';
